# 1. Le decimos el tipo de base de datos
quarkus.datasource.db-kind=postgresql

# 2. Las credenciales de tu Postgres local (CÁMBIALAS por las tuyas)
quarkus.datasource.username=postgres
quarkus.datasource.password=superadmin
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/multas

quarkus.hibernate-orm.database.generation=none

quarkus.jwt.verify.issuer=https://multas.com/issuer
mp.jwt.verify.issuer=https://multas.com/issuer

quarkus.http.host=0.0.0.0



